class PrudImages {
  String logo;
  String intro1;
  String intro2;
  String intro3;
  String intro4;
  String intro5;
  String intro;
  String prudIcon;
  String like;
  String dislike;
  String settings;
  String screen;
  String plainScreen;
  String bg;
  String user;
  String err;
  String support;
  String document;
  String front1;
  String front2;
  String front3;
  String front4;
  String front5;
  String front6;
  String front7;
  String front8;
  String front9;
  String front10;
  String front11;
  String front12;
  String front13;
  String front14;
  String front15;
  String stores;
  String influencerFemale;
  String influencerMale;
  String watchVideo;
  String videoAd;
  String adLight;
  String adDark;
  String announceMsg;
  String announceMsgColor;
  String announceMsgMega;
  String announceMsgMegaColor;
  String promo;
  String shortener;
  String account;
  String shipper;
  String sparks;
  String newSpark;
  String mySparks;
  String income;
  String wallet;
  String promotions;
  String points;
  String links;
  String utility;
  String utilities;
  String travel;
  String travel1;
  String transport;
  String bus;
  String smartTv;
  String smartTv1;
  String resort;
  String power;
  String power1;
  String hotel;
  String flight;
  String airtime;



  PrudImages({
    required this.front1,
    required this.front2,
    required this.front3,
    required this.front4,
    required this.front5,
    required this.front6,
    required this.front7,
    required this.front8,
    required this.front9,
    required this.front10,
    required this.front11,
    required this.front12,
    required this.front13,
    required this.front14,
    required this.front15,
    required this.err,
    required this.logo,
    required this.intro1,
    required this.intro2,
    required this.intro3,
    required this.intro4,
    required this.intro5,
    required this.intro,
    required this.prudIcon,
    required this.like,
    required this.dislike,
    required this.screen,
    required this.settings,
    required this.user,
    required this.support,
    required this.document,
    required this.bg,
    required this.stores,
    required this.influencerFemale,
    required this.influencerMale,
    required this.watchVideo,
    required this.videoAd,
    required this.adLight,
    required this.adDark,
    required this.announceMsg,
    required this.announceMsgColor,
    required this.announceMsgMega,
    required this.announceMsgMegaColor,
    required this.promo,
    required this.account,
    required this.shipper,
    required this.shortener,
    required this.sparks,
    required this.newSpark,
    required this.mySparks,
    required this.plainScreen,
    required this.points,
    required this.links,
    required this.income,
    required this.promotions,
    required this.wallet,
    required this.airtime,
    required this.bus,
    required this.flight,
    required this.hotel,
    required this.power,
    required this.power1,
    required this.resort,
    required this.smartTv,
    required this.smartTv1,
    required this.transport,
    required this.travel,
    required this.travel1,
    required this.utilities,
    required this.utility
  });
}

PrudImages prudImages = PrudImages(
  front1: 'assets/images/carousels/1.jpg',
  front2: 'assets/images/carousels/2.jpg',
  front3: 'assets/images/carousels/3.jpg',
  front4: 'assets/images/carousels/4.jpg',
  front5: 'assets/images/carousels/5.jpg',
  front6: 'assets/images/carousels/6.jpg',
  front7: 'assets/images/carousels/7.jpg',
  front8: 'assets/images/carousels/8.jpg',
  front9: 'assets/images/carousels/9.jpg',
  front10: 'assets/images/carousels/10.jpg',
  front11: 'assets/images/carousels/11.jpg',
  front12: 'assets/images/carousels/12.jpg',
  front13: 'assets/images/carousels/13.jpg',
  front14: 'assets/images/carousels/14.jpg',
  front15: 'assets/images/carousels/15.jpg',
  dislike: 'assets/images/dislike.png',
  err: 'assets/images/err.jpg',
  intro: 'assets/images/intros/intro.jpg',
  intro1: 'assets/images/intros/intro1.jpg',
  intro2: 'assets/images/intros/intro2.jpg',
  intro3: 'assets/images/intros/intro3.jpg',
  intro4: 'assets/images/intros/intro4.jpg',
  intro5: 'assets/images/intros/intro5.jpg',
  like: 'assets/images/like.png',
  logo: 'assets/images/prud_logo.png',
  prudIcon: 'assets/images/prudapp_icon.png',
  screen: 'assets/images/gh.jpg',
  plainScreen: 'assets/images/plain_gh.jpg',
  bg: 'assets/images/gg.jpg',
  settings: 'assets/images/settings.png',
  user: 'assets/images/user.png',
  support: 'assets/images/call-center.png',
  document: 'assets/images/document.png',
  stores: 'assets/images/supermaket.png',
  influencerFemale: 'assets/images/influencer-1.png',
  influencerMale: 'assets/images/influencer.png',
  watchVideo: 'assets/images/video.png',
  videoAd: 'assets/images/video-ad.png',
  adLight: 'assets/images/tv.png',
  adDark: 'assets/images/tv-1.png',
  announceMsg: 'assets/images/message.png',
  announceMsgColor: 'assets/images/message-1.png',
  announceMsgMega: 'assets/images/megaphone-1.png',
  announceMsgMegaColor: 'assets/images/megaphone.png',
  promo: 'assets/images/promotion.png',
  shipper: 'assets/images/delivery.png',
  account: 'assets/images/account.png',
  shortener: 'assets/images/link.png',
  sparks: 'assets/images/subscriber.png',
  newSpark: "assets/images/subscribe.png",
  mySparks: "assets/images/subscribe1.png",
  points: 'assets/images/marketing.png',
  links: 'assets/images/link1.png',
  income: "assets/images/passive-income.png",
  promotions: "assets/images/discount.png",
  wallet: "assets/images/wallet.png",
  airtime: "assets/images/airtime.png",
  flight: "assets/images/flight.png",
  hotel: "assets/images/hotel.png",
  power: "assets/images/power.png",
  power1: "assets/images/power1.png",
  resort: "assets/images/resort.png",
  smartTv: "assets/images/smartTv.png",
  smartTv1: "assets/images/smartTv1.png",
  bus: "assets/images/tour-bus.png",
  transport: "assets/images/transport.png",
  travel: "assets/images/travel.png",
  travel1: "assets/images/travel1.png",
  utility: "assets/images/utility.png",
  utilities: "assets/images/utilities.png",
);
