class PrudImages {
  String logo;
  String intro1;
  String intro2;
  String intro3;
  String intro4;
  String intro5;
  String intro;
  String prudIcon;
  String like;
  String dislike;
  String settings;
  String screen;
  String plainScreen;
  String bg;
  String user;
  String err;
  String support;
  String document;
  String front1;
  String front2;
  String front3;
  String front4;
  String front5;
  String front6;
  String front7;
  String front8;
  String front9;
  String front10;
  String front11;
  String front12;
  String front13;
  String front14;
  String front15;
  String front16;
  String front17;
  String front18;
  String front19;
  String front20;
  String front21;
  String influencerFemale;
  String influencerMale;
  String watchVideo;
  String videoAd;
  String adLight;
  String adDark;
  String announceMsg;
  String announceMsgMega;
  String promo;
  String shortener;
  String account;
  String income;
  String wallet;
  String promotions;
  String points;
  String links;
  String smartTv;
  String smartTv1;
  String history;
  String avatar_1;
  String avatar_2;
  String avatar_3;
  String avatar_4;
  String likedVideo;
  String localVideoLibrary;
  String videoMembership;
  String videoSearch;
  String prudVid;
  String videoHome;
  String prudVidStudio;
  String playlist;
  String live;
  String prudVider;
  String studio;
  String stream;
  String streamDark;
  String streamStudio;
  String streamStudioDark;
  String thriller;
  String thrillerDark;
  String operators;
  String movie;
  String music;
  String news;
  String learn;
  String cuisine;
  String comedy;
  String addOperator;
  String subscriber;
  String subscribe;
  String videos;
  String predict;



  PrudImages({
    required this.front1,
    required this.studio,
    required this.live,
    required this.front2,
    required this.front3,
    required this.front4,
    required this.front5,
    required this.front6,
    required this.front7,
    required this.front8,
    required this.front9,
    required this.front10,
    required this.front11,
    required this.front12,
    required this.front13,
    required this.front14,
    required this.front15,
    required this.front16,
    required this.front17,
    required this.front18,
    required this.front19,
    required this.front20,
    required this.front21,
    required this.err,
    required this.operators,
    required this.logo,
    required this.intro1,
    required this.intro2,
    required this.intro3,
    required this.intro4,
    required this.intro5,
    required this.intro,
    required this.prudIcon,
    required this.like,
    required this.dislike,
    required this.screen,
    required this.settings,
    required this.user,
    required this.support,
    required this.document,
    required this.bg,
    required this.influencerFemale,
    required this.influencerMale,
    required this.watchVideo,
    required this.videoAd,
    required this.adLight,
    required this.adDark,
    required this.announceMsg,
    required this.announceMsgMega,
    required this.promo,
    required this.account,
    required this.shortener,
    required this.plainScreen,
    required this.points,
    required this.links,
    required this.income,
    required this.promotions,
    required this.wallet,
    required this.smartTv,
    required this.smartTv1,
    required this.stream,
    required this.streamDark,
    required this.streamStudio,
    required this.streamStudioDark,
    required this.history,
    required this.avatar_1,
    required this.avatar_2,
    required this.avatar_3,
    required this.avatar_4,
    required this.playlist,
    required this.likedVideo,
    required this.localVideoLibrary,
    required this.videoMembership,
    required this.videoSearch,
    required this.prudVid,
    required this.videoHome,
    required this.prudVidStudio,
    required this.prudVider,
    required this.thriller,
    required this.thrillerDark,
    required this.cuisine,
    required this.movie,
    required this.music,
    required this.learn,
    required this.news,
    required this.comedy,
    required this.addOperator,
    required this.subscriber,
    required this.subscribe,
    required this.videos,
    required this.predict
  });
}

PrudImages prudImages = PrudImages(
  front1: 'assets/images/carousels/1.jpg',
  front2: 'assets/images/carousels/2.jpg',
  front3: 'assets/images/carousels/3.jpg',
  front4: 'assets/images/carousels/4.jpg',
  front5: 'assets/images/carousels/5.jpg',
  front6: 'assets/images/carousels/6.jpg',
  front7: 'assets/images/carousels/7.jpg',
  front8: 'assets/images/carousels/8.jpg',
  front9: 'assets/images/carousels/9.jpg',
  front10: 'assets/images/carousels/10.jpg',
  front11: 'assets/images/carousels/11.jpg',
  front12: 'assets/images/carousels/12.jpg',
  front13: 'assets/images/carousels/13.jpg',
  front14: 'assets/images/carousels/14.jpg',
  front15: 'assets/images/carousels/15.jpg',
  front16: 'assets/images/carousels/16.jpg',
  front17: 'assets/images/carousels/17.jpg',
  front18: 'assets/images/carousels/18.jpg',
  front19: 'assets/images/carousels/19.jpg',
  front20: 'assets/images/carousels/20.jpg',
  front21: 'assets/images/carousels/21.jpg',
  dislike: 'assets/images/dislike.png',
  err: 'assets/images/err.jpg',
  intro: 'assets/images/intros/intro.jpg',
  intro1: 'assets/images/intros/intro1.jpg',
  intro2: 'assets/images/intros/intro2.jpg',
  intro3: 'assets/images/intros/intro3.jpg',
  intro4: 'assets/images/intros/intro4.jpg',
  intro5: 'assets/images/intros/intro5.jpg',
  like: 'assets/images/like.png',
  logo: 'assets/images/prud_logo.png',
  prudIcon: 'assets/images/prudapp_icon.png',
  screen: 'assets/images/gh.jpg',
  plainScreen: 'assets/images/plain_gh.jpg',
  bg: 'assets/images/gg.jpg',
  settings: 'assets/images/settings.png',
  user: 'assets/images/user.png',
  support: 'assets/images/call-center.png',
  document: 'assets/images/document.png',
  influencerFemale: 'assets/images/influencer-1.png',
  influencerMale: 'assets/images/influencer.png',
  watchVideo: 'assets/images/video.png',
  videoAd: 'assets/images/video-ad.png',
  adLight: 'assets/images/tv.png',
  adDark: 'assets/images/tv-1.png',
  announceMsg: 'assets/images/message.png',
  stream: 'assets/images/stream.png',
  announceMsgMega: 'assets/images/megaphone-1.png',
  streamDark: 'assets/images/stream-dark.png',
  promo: 'assets/images/promotion.png',
  account: 'assets/images/account.png',
  shortener: 'assets/images/link.png',
  subscriber: 'assets/images/subscriber.png',
  subscribe: "assets/images/subscribe.png",
  videos: "assets/images/subscribe1.png",
  points: 'assets/images/marketing.png',
  links: 'assets/images/link1.png',
  income: "assets/images/passive-income.png",
  promotions: "assets/images/discount.png",
  wallet: "assets/images/wallet.png",
  streamStudio: "assets/images/stream-studio.png",
  streamStudioDark: "assets/images/stream-studio-dark.png",
  thriller: "assets/images/thriller.png",
  thrillerDark: "assets/images/thriller-dark.png",
  smartTv: "assets/images/smart-tv.png",
  smartTv1: "assets/images/smart-tv1.png",
  history: "assets/images/history.png",
  avatar_1: "assets/images/woman1.png",
  avatar_2: "assets/images/woman.png",
  avatar_3: "assets/images/boy.png",
  avatar_4: "assets/images/man.png",
  addOperator: "assets/images/add-friend.png",
  operators: "assets/images/management.png",
  likedVideo: "assets/images/likedVideo.png",
  localVideoLibrary: "assets/images/localVideoLibrary.png",
  videoMembership: "assets/images/videoMembership.png",
  videoSearch: "assets/images/videoSearch.png",
  prudVid: "assets/images/prudVid.png",
  videoHome: "assets/images/videoHome.png",
  prudVidStudio: "assets/images/prudVidStudio.png",
  playlist: "assets/images/playlist.png",
  live: "assets/images/live.png",
  prudVider: "assets/images/prudVider.png",
  studio: "assets/images/studio.png",
  music: "assets/images/music.png",
  movie: "assets/images/movie.png",
  comedy: "assets/images/comedy.png",
  learn: "assets/images/learn.png",
  news: "assets/images/world-news.png",
  cuisine: "assets/images/cuisine.png",
  predict: "assets/images/prediction.png",
);
